# permissions for end users to view egressipams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: egressipam-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - egressipams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - egressipams/status
  verbs:
  - get
