# permissions for end users to edit namespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - namespaces/status
  verbs:
  - get
