# permissions for end users to view namespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - namespaces/status
  verbs:
  - get
